version: '3.3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '127.0.0.1:9000:9000'
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - HOST=127.0.0.1
      - PORT=9000
      - FILE_CACHE_DB=./data/cache.db
      - WEB_GENERATOR_API_URL=http://127.0.0.1:9001
      - WEB_OUTPUT_PATH=./data/website
    command: yarn start server
